package com.example.myanimelist.utils

const val REGISTER = "views/registro-view.fxml"
const val LOGIN = "views/inicioSesion-view.fxml"
const val SPLASH = "views/splash-view.fxml"
const val ABOUT = "views/acerca-de-view.fxml"
const val MAIN_USER_MYLIST = "views/main-user-myList-view.fxml"
const val MAIN_USER_ANIME = "views/main-user-anime-view.fxml"
const val MAIN_ADMIN = "views/main-admin-view.fxml"
const val MAIN_USER_STATS = "views/main-user-stats-view.fxml"
const val ADMIN_USERS_LIST = "views/usuarios-admin-view.fxml"
const val ANIME_DATA = "views/animeData-view.fxml"
const val ANIME_DATA_ADMIN = "views/animeDataAdmin-view.fxml"
const val ANIME_DATA_EDIT = "views/animeEdit-view.fxml"
const val PERFIL_VIEW = "views/perfil-user-view.fxml"
const val PERFIL_VIEW_ADMIN = "views/perfil-admin-view.fxml"
const val ADD_ANIME = "views/admin-add-anime-view.fxml"